---
- name: Ensure docker_compose lib folder exists
  file:
    path: "{{ docker_compose_install_path }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  become: true

- name: Download docker_compose archive
  get_url:
    url: "{{ docker_compose_download_url }}"
    dest: "{{ docker_compose_path }}"
    mode: 0655
    checksum: "{{ docker_compose_checksum }}"
  become: true

- name: Create docker_compose symlink
  file:
    src: "{{ docker_compose_path }}"
    dest: "{{ docker_compose_bin }}"
    owner: root
    group: root
    state: link
    force: true
  become: true
